### ISSUE TITLE
Top bar fixes

### ISSUE THREAD

**Issue by cojofra** [Autodesk/genetic-constructor#1242]
- [ ] Genetic constructor title 16pt and bold
- [ ] new G icon 
- [ ] user menu needs user.svg icon

**Comment by cojofra** [comment]
@jlachoff can't find the G icon asset in the box folder - could you post the link/name here?

**Comment by jlachoff** [comment]
https://autodesk.box.com/s/2gzootmhcf6hilutox06phv2wx64lbxn

It's called "main_logo.svg" - the logo is white, and since it's on a transparent background it previews as just white, but when it's put on a dark background it works. (I can make it a different color, but then @duncanmeech will need to re-style it... which is fine too.)

**Comment by cojofra** [comment]
thanks @jlachoff perfect!
