### ISSUE TITLE
Panel Navigation fixes

### ISSUE THREAD

**Issue by cojofra** [Autodesk/genetic-constructor#1251]
- [ ] reorder on the left: info, shopping, version, setting, plugin, help, feedback
 - [x] hide version
 - [x] collapse state loses all highlight
 - [ ] collapse state will be dark with light grey icons https://autodesk.box.com/s/w26feeai98p67jj8xa7psowkggdms8xa
 - [ ] column space below icon panel should be background color #1d222d

**Comment by duncanmeech** [comment]
Define 'icon panel' and 'space below" in the last item above.

**Comment by cojofra** [comment]
@jlachoff could you check on the last item? 
these are all still from December - so it may be fixed already.

**Comment by jlachoff** [comment]
Confirmed. The last item is now correct on dev.

**Comment by jlachoff** [comment]
The third item does not appear to have been addressed yet on feature dev. -- the first part was completed (dark background when collapsed), but the dimming back of the icons is not completed. If it's easier to simply add transparency  to the existing white icons in order to accomplish that, please use 20%.

**Comment by jlachoff** [comment]
I commented on the item.

On Feb 7, 2017, at 9:27 AM, Cornelia Scheitz <notifications@github.com<mailto:notifications@github.com>> wrote:


@jlachoff<https://github.com/jlachoff> could you check on the last item?
these are all still from December - so it may be fixed already.
