### ISSUE TITLE
Construct Naming fix

### ISSUE THREAD

**Issue by cojofra** [Autodesk/genetic-constructor#1254]
"New Construct" (default name) gets converted to "New Block" if you just click it once.
It should stay with "New Construct" until the user changes it.
This is also a current bug in production.

**Comment by cojofra** [comment]
in the current feature branch it now always says "New Block" - even when "New Construct" should be there.

**Comment by duncanmeech** [comment]
There was a decision to leave new constructs / blocks unnamed...which causes various components to chose their own defaults. This is especially a problem now that we have search features in project lists since there is no text to search against. I'm going to explicitly name new constructs when they are created.
