### ISSUE TITLE
Hidden Block Selection is Broken

### ISSUE THREAD

**Issue by duncanmeech** [Autodesk/genetic-constructor#1592]
![Screen Shot 2017-02-21 at 7.22.04 PM.png](https://zube.io/files/Autodesk/7e5cabc9b1dfacac255c56a950dd54e4.png)

**Comment by cojofra** [comment]
@duncanmeech I don't see any other issues on qa right now - can you give me an example of what you noticed?

**Comment by maxbates** [comment]
I think this may just be not reflecting disabled + selected simultaneously

**Comment by maxbates** [comment]
@duncanmeech the selection is easy to fix - get the construct and block selected in store.focus, and highlight based on that, not just the block id

**Comment by jlachoff** [comment]
Per our discussion at sprint review today, I'm adding a note here: @cojofra , the current behavior is that selecting hidden blocks with the same ID (technically) selects them visually in multiple constructs simultaneously. This may be technically correct, but it breaks the interaction model since the user cannot select other blocks in just one of the constructs and then preview the sequence. No technical change is requested, but the UI should never do this.

**Comment by cojofra** [comment]
thanks for adding - I need to be better about updating these when we take this to a conversation. 
are we implementing max's suggestion for the fix?
