### ISSUE TITLE
Export of large projects fails

### ISSUE THREAD

**Issue by maxbates** [Autodesk/genetic-constructor#982]
### URL

https://geneticconstructor.bionano.autodesk.com/project/project-6089919f-bad1-451a-83ba-00dd676a0762
### Description

500 at @client.js:39
exporting large project
if you take the first large combinatorial out it works
### User

4edc23d0-84f6-11e6-9afe-812b5af947d7

**Comment by maxbates** [comment]
@jlachoff how do you want to handle this? E.g. when you have a project that would generate a million genbanks, should we just export the CSV? we can't generate the million combinations and a file for each ourselves

**Comment by jlachoff** [comment]
Just to clarify: Is the use case here that the user is selecting Download > All Combinations? If so, I think we need to consider whether even a CSV is a realistic experience, since a CSV with that much data in it will likely be huge and crash excel or whatever, anyhow. Perhaps this fits into the category of "long list support" - (I get it that it doesn't necessarily only happen with long lists).
